# Generated by Django 4.2.7 on 2026-07-17 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_add_outbox_event_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCountProjection',
            fields=[
                ('service_id', models.UUIDField(primary_key=True, serialize=False)),
                ('active_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalResponsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('DOS', 'Directeur des Opérations'), ('DES', 'Directeur Engineering'), ('DO', 'Directeur Opérationnel'), ('DE', 'Directeur Engineering'), ('DA', 'Directeur Adjoint'), ('CS', 'Chef de Service')], max_length=3)),
                ('reports_to_user_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('POLE', 'Pôle'), ('DIRECTION', 'Direction'), ('SERVICE', 'Service')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, choices=[('OPERATIONNEL', 'Opérationnel'), ('ENGINEERING', 'Engineering')], help_text='Défini uniquement pour les Directions.', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='org_outboxe_is_publ_c3ab92_idx',
            old_name='org_outboxe_is_publ_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.OneToOneField(limit_choices_to={'type': 'SERVICE'}, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='org.organizationalunit'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['type'], name='org_organiz_type_461baf_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['is_active'], name='org_organiz_is_acti_d8372a_idx'),
        ),
        migrations.AddField(
            model_name='organizationalresponsibility',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='org.organizationalunit'),
        ),
        migrations.AddIndex(
            model_name='organizationalresponsibility',
            index=models.Index(fields=['unit', 'role', 'ended_at'], name='org_organiz_unit_id_90c3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalresponsibility',
            index=models.Index(fields=['user_id'], name='org_organiz_user_id_8dbc36_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationalresponsibility',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'DOS')), fields=('role',), name='unique_active_dos'),
        ),
        migrations.AddConstraint(
            model_name='organizationalresponsibility',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'DES')), fields=('role',), name='unique_active_des'),
        ),
        migrations.AddConstraint(
            model_name='organizationalresponsibility',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role__in', ['DO', 'DE'])), fields=('unit', 'role'), name='unique_active_do_de_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='organizationalresponsibility',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'CS')), fields=('unit', 'role'), name='unique_active_cs_per_service'),
        ),
    ]
