# Generated by Django 5.0.6 on 2026-07-15 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('identifiant_ad', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('nom_complet', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_credentials',
            },
        ),
        migrations.CreateModel(
            name='AuthHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('token_refresh', 'Rafraîchissement de token'), ('password_reset', 'Réinitialisation de mot de passe'), ('account_locked', 'Compte verrouillé')], max_length=30)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_history',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('revoque', models.BooleanField(default=False)),
                ('ip_creation', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
    ]
